### ISSUE TITLE
Codebase issue setting password

### ISSUE THREAD

**Issue by mart-ar** [MPSystemsServices/CodeBase-for-DBF#11]
I would appreciate if anyone could help me please, I've taken over the support of a Codebase 6 system, a system I'm not very familiar with, and I'm having trouble setting myself up as a user.  I have created my account using Account Manager in CBAdmin and have set a password, but when I try to log into the system using my name I get an error:
**Invalid Password Authorization Error (access denied)
code4userConnect**

I know that my username is recognised because if I put a random name that's not set up, I get a different error "Invalid UserID Authorization Error", but I don't get that for my own name. 

I've tried changing my password several times, tried setting my password to be the same as another user with whose name I can get access, but nothing works. 

I'm wondering if there a need to flush the password update through when it's been updated or something like that?  Any pointers appreciated.

**Comment by trevster344** [comment]
Have you tried opening the account4.dbf file with foxpro or some other compatible viewer to verify the password is exactly what you think it is? My knowledge is limited when it comes to the server unfortunately so correct me if you do not have that file.

**Comment by mart-ar** [comment]
You're a star Trev! I wasn't aware that passwords are stored there, it took me a while to get everyone off to copy the account4 table and check it, but when I did I found that my password was blank! It seems that CBAdmin didn't actually set the password despite my many attempts. 
Thank you!

**Comment by mart-ar** [comment]
Problem solved with the help of trevster344. Much appreciated
