### ISSUE TITLE
Integer(AutoInc) Visual FoxPro field

### ISSUE THREAD

**Issue by bruscain** [MPSystemsServices/CodeBase-for-DBF#6]
Is it possible to create a table with Integer(AutoInc) field?

**Comment by MPSystemsServices** [comment]
CodeBase does not support Visual FoxPro type auto incremented fields.  CodeBase has its own format for auto incrementing fields, which you can explore with the extended documentation.  VFP and Clipper are not able to read tables that have CodeBase auto-increment type fields in them, or if they do, you run the risk of data corruption.

An interesting To-Do might be for someone to adapt this open source version of CodeBase to handle native VFP auto incrementing fields.
